"""Add indexes and TokenBlocklist

Revision ID: 94438ba377ef
Revises: 77de3509645a
Create Date: 2025-12-07 17:28:09.880255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94438ba377ef'
down_revision = '77de3509645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_token_jti', ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_comment_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_comment_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_is_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_post_public_id', ['public_id'], unique=False)
        batch_op.create_index('idx_post_published_at', ['published_at'], unique=False)
        batch_op.create_index('idx_post_status', ['status'], unique=False)
        batch_op.create_index('idx_post_story_type', ['story_type'], unique=False)
        batch_op.create_index('idx_post_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_post_view_count', ['view_count'], unique=False)

    with op.batch_alter_table('supports', schema=None) as batch_op:
        batch_op.create_index('idx_support_giver_id', ['giver_id'], unique=False)
        batch_op.create_index('idx_support_post_id', ['post_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_post_reaction', ['giver_id', 'post_id', 'support_type'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_public_id', ['public_id'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_public_id')
        batch_op.drop_index('idx_user_is_active')
        batch_op.drop_index('idx_user_email')

    with op.batch_alter_table('supports', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_post_reaction', type_='unique')
        batch_op.drop_index('idx_support_post_id')
        batch_op.drop_index('idx_support_giver_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_post_view_count')
        batch_op.drop_index('idx_post_user_id')
        batch_op.drop_index('idx_post_story_type')
        batch_op.drop_index('idx_post_status')
        batch_op.drop_index('idx_post_published_at')
        batch_op.drop_index('idx_post_public_id')
        batch_op.drop_index('idx_post_is_featured')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_user_id')
        batch_op.drop_index('idx_comment_post_id')
        batch_op.drop_index('idx_comment_parent_id')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
        batch_op.drop_index('idx_token_jti')
        batch_op.drop_index('idx_token_expires')

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
