"""Add composite indexes and denormalized counts for query optimization

Revision ID: 3b3c640bb720
Revises: add_engagement_tracking
Create Date: 2025-12-22 17:35:46.423845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c640bb720'
down_revision = 'add_engagement_tracking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=True))
        batch_op.create_index('idx_post_status_published', ['status', 'published_at'], unique=False)
        batch_op.create_index('idx_post_status_story_type', ['status', 'story_type'], unique=False)
        batch_op.create_index('idx_post_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_post_user_status')
        batch_op.drop_index('idx_post_status_story_type')
        batch_op.drop_index('idx_post_status_published')
        batch_op.drop_column('comment_count')
        batch_op.drop_column('support_count')

    # ### end Alembic commands ###
